### ISSUE TITLE
[UI_tests] yarn install doesn't build the project

### ISSUE THREAD

**Issue by nalmabrcom** [eclipse/che-che4z#35]
```
Trace: 
  Error: https://registry.yarnpkg.com/@eclipse%2fche-che4z: Not found
      at Request.params.callback [as _callback] (C:\Program Files (x86)\Yarn\lib\cli.js:66096:18)
      at Request.self.callback (C:\Program Files (x86)\Yarn\lib\cli.js:140748:22)
      at Request.emit (events.js:315:20)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:141720:10)
      at Request.emit (events.js:315:20)
      at IncomingMessage.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:141642:12)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (_stream_readable.js:1221:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by nalmabrcom** [comment]
After some investigation seems that problem is not in the `install` option in `package.json`. 
As we have it not at the root of the project, but in `tests/` IMO it's better not to put the `package.json` to the project's root. Let's leave as it is now.
